[project]
name = "road"
version = "0.0.0"
description = "An open-source platform to shape and reward open-source contributions. Create bounties, prioritize features, and collaborate together."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
